### ISSUE TITLE
Cell merge order is not consistent with other implementations

### ISSUE THREAD

**Issue by resuna** [dbohdan/2048.tcl#6]
In most implementations of 2048 and similar programs, if you have a situation like this:

|[2][2][2]. .. .. .|

And you shift right, you get

|. .. .. .. .[2][4]|

In this implementation you get

|. .. .. .. .[4][2]|

That is, it seems to be scanning left to right looking for cells to merge.

This makes it significantly harder, since it leads to low valued cells accumulating between blocks of high valued cells.

It looks like "forcells" needs an additional parameter indicating the direction of the move, so it can iterate over cells in the inverse direction. That would make the higher level logic merge cells at the edges.

**Comment by dbohdan** [comment]
Good catch! I'll push a fix today.

**Comment by dbohdan** [comment]
I've pushed the fix and a few other changes. Tell me if the current commit works for you; I'll tag it as a release if it does.

**Comment by resuna** [comment]
Absolutely. Much better, less frustrating. 👍

**Comment by dbohdan** [comment]
Great! [Tagged](https://github.com/dbohdan/2048.tcl/releases/tag/v0.4.0).
